/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Model.HangMua;
import Model.HoaDon;
import Model.KhachHang;
import Model.MatHang;
import controller.Controller;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kuted
 */
public class TaoHoaDonFrm extends javax.swing.JDialog {

    /**
     * Creates new form TaoHoaDonFrm
     */
    private HoaDonFrm home;
    private List <HangMua> orderGoods;
    private DefaultTableModel tblModel;
    private KhachHang khachHang;
    private int tongsoluong = 0;
    private int tonggiatien = 0;
    public TaoHoaDonFrm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        home = (HoaDonFrm) parent;
        khachHang = home.getKhachHang();
        orderGoods = new ArrayList<HangMua>();
        tblModel = (DefaultTableModel) tbMatHang.getModel();
        addItemMatHang();
        txtTenKhachHang.setText(khachHang.getHoTenKH());
    }
    private void showData(){
        tblModel.setRowCount(0);
        for(HangMua hangMua : orderGoods){
            tblModel.addRow(new Object[]{
                hangMua.getMatHang().getMaMH(),
                hangMua.getMatHang().getTenMH(),
                hangMua.getMatHang().getLoaiMH(),
                hangMua.getSoluong(),
                hangMua.getTongtien()
            });
        }
    }
    private void addItemMatHang(){
        for(MatHang matHang : Controller.goods){
            cbMatHang.addItem(matHang.toString());
        }
    }
    private void getTonggiavaSoluong(){
        tonggiatien = 0;
        tongsoluong = 0;
        for(HangMua hangMua : orderGoods){
            tonggiatien += hangMua.getTongtien();
            tongsoluong += hangMua.getSoluong();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btThemmathang = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTongsoluong = new javax.swing.JLabel();
        txtTenKhachHang = new javax.swing.JLabel();
        btTaodon = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtTongtien = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMatHang = new javax.swing.JTable();
        cbMatHang = new javax.swing.JComboBox<>();
        txtNhapsoluong = new javax.swing.JTextField();
        btnHuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Tên mặt hàng");

        btThemmathang.setText("Thêm");
        btThemmathang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemmathangActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Tạo hóa đơn");

        jLabel5.setText("Tổng tiền");

        jLabel2.setText("Tên khách hàng");

        txtTongsoluong.setText("0");

        txtTenKhachHang.setText("Tên");

        btTaodon.setText("Tạo đơn");
        btTaodon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTaodonActionPerformed(evt);
            }
        });

        jLabel7.setText("Số lượng");

        txtTongtien.setText("0");

        tbMatHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã mặt hàng", "Tên mặt hàng", "Loại", "Số lượng", "Giá tiền"
            }
        ));
        jScrollPane1.setViewportView(tbMatHang);

        cbMatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMatHangActionPerformed(evt);
            }
        });

        txtNhapsoluong.setText("1");
        txtNhapsoluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNhapsoluongActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbMatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(29, 29, 29)
                                                .addComponent(txtNhapsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btThemmathang))))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTongsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btTaodon)
                        .addGap(41, 41, 41)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMatHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNhapsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btThemmathang))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTongsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btTaodon)
                    .addComponent(btnHuy))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btThemmathangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemmathangActionPerformed

       // TODO add your handling code here:
        if(Controller.goods.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Chưa thêm mặt hàng");
            return;
        }
        MatHang mh = Controller.goods.get(cbMatHang.getSelectedIndex());
        int soluong = 0;
        try{
            soluong = Integer.parseInt(txtNhapsoluong.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "phải nhập số");
        }catch (Exception e){
            e.printStackTrace();
        }
        int count = 0;
        for(HangMua hangMua : orderGoods){
            if(hangMua.getMatHang().getMaMH() == mh.getMaMH()){
                count += hangMua.getSoluong();
            }
        }
        if(count != 0){
            for(HangMua hangMua : orderGoods){
                if(hangMua.getMatHang().getMaMH() == mh.getMaMH()){
                    hangMua.setSoluong(soluong + count);
                }
            }
        }
        else{
            HangMua hangMua = new HangMua(soluong, mh);
            orderGoods.add(hangMua);
        }
        getTonggiavaSoluong();
        showData();
        txtTongsoluong.setText(tongsoluong + "");
        txtTongtien.setText(tonggiatien + "");
    }//GEN-LAST:event_btThemmathangActionPerformed

    private void btTaodonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTaodonActionPerformed
        // TODO add your handling code here:
        if(orderGoods.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Chưa thêm mặt hàng");
            return;
        }
        Controller.setCodestaticHoaDon(Controller.getIdLastInListHoaDon(Controller.bills));
        int id = HoaDon.code;
        Date date = new Date();

        HoaDon hoaDon = new HoaDon(id, khachHang, date, orderGoods, tongsoluong, tonggiatien);
        home.addHoaDon(hoaDon);
        JOptionPane.showMessageDialog(rootPane, "Tạo đơn thành công");
        dispose();
    }//GEN-LAST:event_btTaodonActionPerformed

    private void cbMatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMatHangActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbMatHangActionPerformed

    private void txtNhapsoluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNhapsoluongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNhapsoluongActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaoHoaDonFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaoHoaDonFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaoHoaDonFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaoHoaDonFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaoHoaDonFrm dialog = new TaoHoaDonFrm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTaodon;
    private javax.swing.JButton btThemmathang;
    private javax.swing.JButton btnHuy;
    private javax.swing.JComboBox<String> cbMatHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbMatHang;
    private javax.swing.JTextField txtNhapsoluong;
    private javax.swing.JLabel txtTenKhachHang;
    private javax.swing.JLabel txtTongsoluong;
    private javax.swing.JLabel txtTongtien;
    // End of variables declaration//GEN-END:variables
}
